### PR TITLE
Fix PHP 8.3 breakage by declaring missing properties

### PR DESCRIPTION
**Pull request by dlangille**
fixes https://github.com/flack/UniversalFeedCreator/issues/16

### CODE REVIEW

**Comment by flack** [comment]
Thanks for the PR!

Do you think there is any way to trigger the errors you're seeing in unit tests? When I run phpunit locally on PHP 8.3.1, I get no notices (granted, we don't really have a lot of test coverage, but maybe it's easy to add something for this)

**Comment by flack** [comment]
P.S.: Looking at the source code, both `_timeout` and `truncSize` are never read, they are only set. I wonder if we could simply remove them instead (then we also wouldn't need tests for that :-))

**Comment by dlangille** [comment]
> P.S.: Looking at the source code, both `_timeout` and `truncSize` are never read, they are only set. I wonder if we could simply remove them instead (then we also wouldn't need tests for that :-))

Unless your users have become accustomed to using it. ;) I checked my code, I'm not using it.

**Comment by dlangille** [comment]
> Thanks for the PR!
> 
> Do you think there is any way to trigger the errors you're seeing in unit tests? When I run phpunit locally on PHP 8.3.1, I get no notices (granted, we don't really have a lot of test coverage, but maybe it's easy to add something for this)

At https://www.freshports.org - search for newsfeed, which takes you to:

https://www.freshports.org/backend/newsfeeds.php

Clicking on https://www.freshports.org/backend/news.php generated the first error.

Then I clicked on https://www.freshports.org/backend/ - At this URL, when invoking `opml` (I think), it generated the second error.

https://github.com/FreshPorts/freshports/blob/main/www/backend/news.php is the main URL

https://github.com/FreshPorts/freshports/blob/main/classes/newsfeed.php#L60 is my main generation script

**Comment by flack** [comment]
> Unless your users have become accustomed to using it. ;) I checked my code, I'm not using it.

well, strictly speaking your change is also breaks backwards compatibility, because these variables were implicitly public before. I guess a good compromise solution might be to remove `truncSize` (which obviously was copy n pasted between classes), anyone who needs the value of `500` can just set that in their own child class. `_timeout` we can keep as a protected variable like you suggest, because it's kind of part of the method signature, and who knows, maybe this is actually useful for some child classes somewhere

**Pull request merged**
