### PR TITLE
For Yandex Turbo Pages

### PR DESCRIPTION
**Pull request by Dr-Yukon**
Addition of <item turbo="true"> for [Yandex Turbo Pages](https://yandex.ru/dev/turbo/doc/rss/simple-rss-docpage/), a mobile browsing accelerator through RSS feed

### CODE REVIEW

**Comment by flack** [comment]
Hello & thanks for the PR! 

I'm not familiar with this feature, I just looked at the documentation shortly, and I wonder: Is it really ok to set the `turbo="true"` attribute unconditionally? For what I understand from the documentation, it looks like you will also have to add a `<turbo:content>` tag for it to work. So if i merge this as is, every feed would send the turbo attribute, but without the necessary extra markup. So isn't it maybe better to make this a configuration option?

**Comment by Dr-Yukon** [comment]
Oh, yes.

**Comment by Dr-Yukon** [comment]
In my case, your tool inserted in Dokuwiki/vendor/ folder, so I need to fix code directly, anyway

**Comment by Dr-Yukon** [comment]
> <turbo:content>
I begin to understand, why YTP does not work yet :D

**Comment by flack** [comment]
Closing for now. Feel free to reopen once you have a working version!

**Pull request closed without merging**
